#!/bin/sh

set -e

# empty message of the day.
# echo -n > /etc/motd

# remove some unused packages
DEBIAN_FRONTEND=noninteractive apt-get purge -y laptop-detect tasksel emacsen-common ienglish-common ispell

# install some additional packages
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends linux-headers-amd64 openssh-server sudo time openssl gnutls-bin zip unzip bzip2 lynx vim vim-scripts curl whois net-tools patch telnet sqlite3 strace lsof less screen rsync git git-lfs dos2unix myrepos traceroute bash-completion socat busybox psmisc man-db dnsutils unattended-upgrades gpg-agent gnupg software-properties-common tcpdump make gzrt jq bash zsh htop dbus-user-session fuse3 acl python3-venv python3-pip python3-setuptools python3-wheel python3-psutil python3-pylibacl python3-sh python3-prometheus-client rdiff-backup xfsprogs smartmontools htop exa grc bat vim iperf fping termshark curl axel aria2 rclone

# members of `sudo` group are not asked for password.
sed -i 's/^%sudo\tALL=(ALL:ALL) ALL/%sudo\tALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers

# new users should be put into the "users" group
sed -i 's/^USERGROUPS=yes/USERGROUPS=no/' /etc/adduser.conf

# fix the time server configuration
sed -i 's/^#NTP=/NTP=sa.pool.ntp.org/' /etc/systemd/timesyncd.conf

# unpack the postinstall tar file
tar -z -x -C /tmp -f /tmp/postinstall.tar.gz

# install global things and root things
mkdir -m 700 -p /root/.ssh
cp /tmp/postinstall.d/resolv.conf /etc/resolv.conf
cp /tmp/postinstall.d/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades
cp /tmp/postinstall.d/apt.conf.d/20auto-upgrades /etc/apt/apt.conf.d/20auto-upgrades
cp /tmp/postinstall.d/vimrc /root/.vimrc
cp /tmp/postinstall.d/bash_login /root/.bash_login

# add our sudoers file for paul
cp /tmp/postinstall.d/sudoers /etc/sudoers.d/asm
chmod 400 /etc/sudoers.d/asm

# install ssh keys and other things for user
mkdir -m700 -p /home/asm/.ssh
cp /tmp/postinstall.d/authorized_keys /home/paul/.ssh/authorized_keys
cp /tmp/postinstall.d/vimrc /home/asm/.vimrc
cp /tmp/postinstall.d/bash_login /home/asm/.bash_login

# fix permissions on root home directory
chmod 700 /root
chmod 600 /root/.bash_login

# fix permissions on home directory
chown -R asm:asm /home/asm
chmod 700 /home/asm
chmod 600 /home/asm/.bash_login /home/asm/.ssh/authorized_keys
